name: Maven Release

on:
  push:
   tags:
     - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew publish
      env:
        MVN_USER_PUBLISH: ${{ secrets.MVN_USER_PUBLISH }}
        MVN_PASS_PUBLISH: ${{ secrets.MVN_PASS_PUBLISH }}
